language: node_js
node_js:
  - '10'
  - '11'
  - '12'
  - '13'
  - '14'

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

after_script:
  - echo $TRAVIS_TEST_RESULT
  - ./cc-test-reporter after-build --debug --exit-code $TRAVIS_TEST_RESULT

script:
  - npm run build
  - npm run cover

deploy:
  - provider: npm
    email: sprokop1010@seznam.cz
    skip_cleanup: true
    api_key: $NPM_TOKEN
    on:
      tags: true
      repo: stefan-prokop-cz/verify-apple-id-token
